# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  admin.papernet.hyperfabrics.com:
  peer0.papernet.hyperfabrics.com:
  peer1.papernet.hyperfabrics.com:
  peer2.papernet.hyperfabrics.com:
  

services:
  peer-base:
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_ADDRESSAUTODETECT=true
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start 2> peer-log.log &
    volumes:
    - /var/run/:/host/var/run/

  orderer-base:
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=orderer
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=false
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer 2> orderer.log &
    volumes:
    - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - msp:/var/hyperledger/orderer/msp
    - orderer:/var/hyperledger/production/orderer
    ports:
      - 7050:7050


  orderer:
    container_name: orderer.hyperfabrics.com
    extends:
      service: orderer-base
    enviorment:
       - ORDERER_GENERAL_LOCALMSPID=orderer
    volumes:
       -./commercialpaper-genesis.block:/var/hyperledger/orderer/orderer.genesis.block


  admin.papernet:
    container_name: admin.papernet.hyperfabrics.com
    extends:
      service: peer-base
    environment:
      - CORE_PEER_ID=admin.papernet
      - CORE_PEER_ADDRESS=admin.papernet.hyperfabrics.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=admin.papernet.hyperfabrics.com:7051
      - CORE_PEER_LOCALMSPID=PapernetMSP
      - CORE_CHAINCODE_LOGGING_SHIM=INFO
    volumes:
        - ./msp:/etc/hyperledger/fabric/msp
        - admin.papernet.hyperfabrics.com:/var/hyperledger/production
    ports:
      - 6051:7051
      - 6053:7053
  
    peer0.papernet:
    container_name: peer0.papernet.hyperfabrics.com
    extends:
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.papernet
      - CORE_PEER_ADDRESS=peer0.papernet.hyperfabrics.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.papernet.hyperfabrics.com:7051
      - CORE_PEER_LOCALMSPID=PapernetMSP
      - CORE_CHAINCODE_LOGGING_SHIM=INFO
    volumes:
        - ./msp:/etc/hyperledger/fabric/msp
        - peer0.papernet.hyperfabrics.com:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053
    
    peer1.papernet:
    container_name: peer1.papernet.hyperfabrics.com
    extends:
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.papernet
      - CORE_PEER_ADDRESS=peer1.papernet.hyperfabrics.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.papernet.hyperfabrics.com:7051
      - CORE_PEER_LOCALMSPID=PapernetMSP
      - CORE_CHAINCODE_LOGGING_SHIM=INFO
    volumes:
        - ./msp:/etc/hyperledger/fabric/msp
        - peer1.papernet.hyperfabrics.com:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053
    
    peer2.papernet:
    container_name: peer1.papernet.hyperfabrics.com
    extends:
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.papernet
      - CORE_PEER_ADDRESS=peer1.papernet.hyperfabrics.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.papernet.hyperfabrics.com:7051
      - CORE_PEER_LOCALMSPID=PapernetMSP
      - CORE_CHAINCODE_LOGGING_SHIM=INFO
    volumes:
        - ./msp:/etc/hyperledger/fabric/msp
        - peer1.papernet.hyperfabrics.com:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053
  partyb:
    container_name: irs-partyb
    extends:
      service: peer-base
    environment:
      - CORE_PEER_ID=partyb.peer0
      - CORE_PEER_ADDRESS=irs-partyb:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=irs-partyb:7051
      - CORE_PEER_LOCALMSPID=partyb
    volumes:
        - ./crypto-config/peerOrganizations/partyb.example.com/peers/peer0.partyb.example.com/msp:/etc/hyperledger/fabric/msp
        - peer0.partyb.example.com:/var/hyperledger/production
    ports:
      - 8051:7051
      - 8053:7053

  partyc:
    container_name: irs-partyc
    extends:
      service: peer-base
    environment:
      - CORE_PEER_ID=partyc.peer0
      - CORE_PEER_ADDRESS=irs-partyc:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=irs-partyc:7051
      - CORE_PEER_LOCALMSPID=partyc
    volumes:
        - ./crypto-config/peerOrganizations/partyc.example.com/peers/peer0.partyc.example.com/msp:/etc/hyperledger/fabric/msp
        - peer0.partyc.example.com:/var/hyperledger/production
    ports:
      - 9051:7051
      - 9053:7053


  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=irs-partya:7051
      - CORE_PEER_LOCALMSPID=partya
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/partya.example.com/users/Admin@partya.example.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ../chaincode/:/opt/gopath/src/irscc
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer
      - partya
      - partyb
      - partyc
      - auditor
      - rrprovider
