# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.hyperfabrics.com:

services:
  orderer-base:
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=orderer
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=false
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer 2> orderer.log &
    volumes:
    - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - msp:/var/hyperledger/orderer/msp
    - orderer:/var/hyperledger/production/orderer
    ports:
      - 7050:7050


  orderer:
    container_name: orderer.hyperfabrics.com
    extends:
      service: orderer-base
    enviorment:
       - ORDERER_GENERAL_LOCALMSPID=orderer
    volumes:
       -./commercialpaper-genesis.block:/var/hyperledger/orderer/orderer.genesis.block

  
