# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  commercialpaper:
    external:
      name: commercialpaper-network

services:
  peer:
    image: hyperledger/fabric-peer:$VERSION
    environment:
      - CORE_PEER_LOCALMSPID=PapernetMSP
      - CORE_PEER_ADDRESS=peer:7051
      - CORE_PEER_CHAINCODE_LISTENADDRESS=chaincode:7052
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
      - ORDERER_ADDRESS=192.168.0.1:7050
      - FABRIC_CFG_PATH= /opt/gopath/src/github.com/hyperledger/fabric/peer
      - COMMERCIALPAPER_CHANNEL_BLOCK_0=./commercialpaperchannel_0.block
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_NETWORKID= commercialpaper-network
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_ADDRESSAUTODETECT=true    
      - CORE_CHAINCODE_LOGGING_SHIM=INFO
      - CORE_METRICS_ENABLED=false
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: chmod 755 * && peer node start 2> peer.log &
    volumes:
    -  /var/run/:/host/var/run/
    - ./:/opt/gopath/src/github.com/hyperledger/fabric/peer

  chaincode:
    image: hyperledger/fabric-nodeenv:$NODEENV_TAG
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_ID=peer
      - CORE_PEER_ADDRESS=peer:7051
      - CORE_PEER_LOCALMSPID=PapernetMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp
      - CHAINCODE_LOGGING_LEVEL=info
    working_dir: /opt/gopath/src/chaincode
    command: /bin/bash -c 'sleep 6000000'
    volumes:
        -  /var/run/:/host/var/run/
        - ./msp:/etc/hyperledger/msp
        - ./contract:/opt/gopath/src/chaincode

  couchdb: 
    image: hyperledger/fabric-couchdb:$BASE_DOCKER_TAG
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    working_dir: /opt/gopath/src/chaincode



  cli: 
    container_name: cli.papernet.hyperfabrics.com
    image: hyperledger/fabric-tools:$VERSION
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli.papernet
      - CORE_PEER_ADDRESS=peer2.papernet.hyperfabrics.com:7051
      - CORE_PEER_LOCALMSPID=PapernetMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp
    working_dir: /opt/gopath/src/chaincodedev
    command: /bin/bash -c './create-channel.sh'
    volumes:
        - /var/run/:/host/var/run/
        - ./msps/cli:/etc/hyperledger/msp
        - ./contract:/opt/gopath/src/chaincodedev/chaincode
        - ./:/opt/gopath/src/chaincodedev/  
    depends_on:
        - peer2.papernet.hyperfabrics.com
        - couchdb2.papernet.hyperfabrics.com
        - chaincode2.papernet.hyperfabrics.com
    networks:
        - commercialpaper

  
  couchdbadmin.papernet:
    container_name: couchdbadmin.papernet.hyperfabrics.com
    extends:
      service: couchdb
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - 6984:5984
    
  couchdb0.papernet:
    container_name: couchdb0.papernet.hyperfabrics.com
    extends:
      service: couchdb
    ports:
      - 7984:5984
  
  couchdb1.papernet:
    container_name: couchdb1.papernet.hyperfabrics.com
    extends:
      service: couchdb
    ports:
      - 8984:5984
  
  couchdb2.papernet:
    container_name: couchdb2.papernet.hyperfabrics.com
    extends:
      service: couchdb
    ports:
      - 9984:5984

  admin.papernet:
    container_name: admin.papernet.hyperfabrics.com
    extends:
      service: peer
    environment:
      - CORE_PEER_ID=admin.papernet
      - CORE_PEER_ADDRESS=admin.papernet.hyperfabrics.com:7051
      - CORE_PEER_CHAINCODE_LISTENADDRESS=chaincodeadmin.papernet.hyperfabrics.com:7052
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdbadmin.papernet.hyperfabrics.com:5984
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=admin.papernet.hyperfabrics.com:7051
    command: chmod 755 * && ./launch-peer.sh
    volumes:
        - ./:/opt/gopath/src/github.com/hyperledger/fabric/peer
        - ./msps/admin/msp:/etc/hyperledger/fabric/msp
        -  admin.papernet.hyperfabrics.com:/var/hyperledger/production
    ports:
      - 6051:7051
      - 6053:7053
    depends_on:
     - couchdbadmin.papernet.hyperfabrics.com
     - cli.papernet.hyperfabrics.com  
    
    peer0.papernet:
    container_name: peer0.papernet.hyperfabrics.com
    extends:
      service: peer
    environment:
      - CORE_PEER_ID=peer0.papernet
      - CORE_PEER_ADDRESS=peer0.papernet.hyperfabrics.com:7051
      - CORE_PEER_CHAINCODE_LISTENADDRESS=chaincode0.papernet.hyperfabrics.com:7052
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0.papernet.hyperfabrics.com:5984
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.papernet.hyperfabrics.com:7051
    command: chmod 755 * && ./launch-peer.sh
    volumes:
        - ./msps/peer0/msp:/etc/hyperledger/fabric/msp
        -  peer0.papernet.hyperfabrics.com:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053
    depends_on:
     - couchdb0.papernet.hyperfabrics.com
    
    peer1.papernet:
    container_name: peer1.papernet.hyperfabrics.com
    extends:
      service: peer
    environment:
      - CORE_PEER_ID=peer1.papernet
      - CORE_PEER_ADDRESS=peer1.papernet.hyperfabrics.com:7051
      - CORE_PEER_CHAINCODE_LISTENADDRESS=chaincode1.papernet.hyperfabrics.com:7052
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1.papernet.hyperfabrics.com:5984
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.papernet.hyperfabrics.com:7051
    command: chmod 755 * && ./launch-peer.sh
    volumes:
        - ./msps/peer1/msp:/etc/hyperledger/fabric/msp
        -  peer1.papernet.hyperfabrics.com:/var/hyperledger/production
    ports:
      - 8051:7051
      - 8053:7053
    depends_on:
     - couchdb1.papernet.hyperfabrics.com
    
    peer2.papernet:
    container_name: peer2.papernet.hyperfabrics.com
    extends:
      service: peer
    environment:
      - CORE_PEER_ID=peer2.papernet
      - CORE_PEER_ADDRESS=peer2.papernet.hyperfabrics.com:7051
      - CORE_PEER_CHAINCODE_LISTENADDRESS=chaincode2.papernet.hyperfabrics.com:7052
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2.papernet.hyperfabrics.com:5984
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.papernet.hyperfabrics.com:7051
    command: chmod 755 * && ./launch-peer.sh
    volumes:
        - ./msps/peer2/msp:/etc/hyperledger/fabric/msp
        - peer2.papernet.hyperfabrics.com:/var/hyperledger/production
    ports:
      - 9051:7051
      - 9053:7053
    depends_on:
     - couchdb2.papernet.hyperfabrics.com


    chaincode.admin:
    container_name: chaincodeadmin.papernet.hyperfabrics.com
    extends:
      service: chaincode
    environment:
      - CORE_PEER_ID=admin.papernet
      - CORE_PEER_ADDRESS=admin.papernet.hyperfabrics.com:7051
    volumes:
        - ./msps/admin/msp:/etc/hyperledger/msp
    ports: 
      - 6052:7052
    depends_on:
     - admin.papernet.hyperfabrics.com
     - couchdbadmin.papernet.hyperfabrics.com
   
    chaincode.peer0:
    container_name: chaincode0.papernet.hyperfabrics.com
    extends:
      service: chaincode
    environment:
      - CORE_PEER_ID=peer0.papernet
      - CORE_PEER_ADDRESS=peer0.papernet.hyperfabrics.com:7051
    volumes:
      - ./msps/peer0/msp:/etc/hyperledger/msp
    ports: 
      - 7052:7052
    depends_on:
     - peer0.papernet.hyperfabrics.com
     - couchdb0.papernet.hyperfabrics.com
    
    chaincode.peer1:
    container_name: chaincode1.papernet.hyperfabrics.com
    extends:
      service: chaincode
    environment:
      - CORE_PEER_ID=peer1.papernet
      - CORE_PEER_ADDRESS=peer1.papernet.hyperfabrics.com:7051
    volumes:
      - ./msps/peer1/msp:/etc/hyperledger/msp
    ports: 
      - 8052:7052
    depends_on:
     - peer1.papernet.hyperfabrics.com
     - couchdb1.papernet.hyperfabrics.com

    chaincode.peer2:
    container_name: chaincode2.papernet.hyperfabrics.com
    extends:
      service: chaincode
    environment:
      - CORE_PEER_ID=peer2.papernet
      - CORE_PEER_ADDRESS=peer2.papernet.hyperfabrics.com:7051
    volumes:
      - ./msps/peer2/msp:/etc/hyperledger/msp
    ports: 
      - 9052:7052
    depends_on:
     - peer2.papernet.hyperfabrics.com
     - couchdb2.papernet.hyperfabrics.com


      

      

    
