version: '2'

services:
 fabric-ca-client:
   image: hyperledger/fabric-ca:1.4.1
   container_name: ca.digibank.hyperfabrics.com
   restart: always
   environment:
    - FABRIC_CA_CLIENT_HOME=/etc/hyperledger/fabric-ca-client
    - FABRIC_CA_CLIENT_CSR_CN=caclient.digibank.hyperfabrics.com
    - FABRIC_CA_CLIENT_URL=http://caserver.digibank.hyperfabrics.com:7054
    - FABRIC_CA_CLIENT_CANAME=caserver.digibank.hyperfabrics.com
    - FABRIC_CA_BCSSP_SW_FILEKEYSTORE_KEYSTORE=/etc/hyperledger/fabric-ca-client/msp/keystore
    - FABRIC_CA_CLIENT_TLS_ENABLED=false
    - FABRIC_CA_CLIENT_TLS_CERTFILE=/etc/hyperledger/fabric-ca-client/tls/ca-cert.pem
    - FABRIC_CA_CLIENT_TLS_KEYFILE=/etc/hyperledger/fabric-ca-client/tls/prtivate.key
    - FABRIC_CA_CLIENT_MSPDIR=/etc/hyperledger/fabric-ca-client/msp
    - FABRIC_CA_KEYFILE=/etc/hyperledger/fabric-ca-client/msp/key.pem
    - FABRIC_CA_CERTFILE=/etc/hyperledger/fabric-ca-client/msp/cert.pem
    - FABRIC_CA_CHAINFILE=/etc/hyperledger/fabric-ca-client/msp/cert.pem
    - FABRIC_CA_SERVER_PORT=7055
    - FABRIC_CA_SERVER_TLS_ENABLED=false
    - FABRIC_CA_SERVER_VERSION=1.4.1
   working_dir: /etc/hyperledger/fabric-ca-client
   #command: /bin/bash -c 'fabric-ca-client enroll -u http://ca.digibank.hyperfabrics.com:Digibankpw@caclient.papernet.hyperfabrics.com:7055  --id.affiliation digibank  --id.attrs admin=true:ecert,hf.Registrar.Roles=*,hf.Registrar.DelegateRoles=*,hf.Revoker=true,hf.IntermediateCA=true,hf.GenCRL=true,hf.Registrar.Attributes=*,hf.AffiliationMgr=t && sleep 60000000'
   #volumes:
    #  - ./msps:/etc/hyperledger/fabric-ca-client/msps
   ports:
    - "7056:7055"