version: '2'

services:
 fabric-ca-client:
   image: hyperledger/fabric-ca:1.4.1
   container_name: caclient.papernet.hyperfabrics.com
   restart: always
   environment:
    - FABRIC_CA_CLIENT_HOME=/etc/hyperledger/fabric-ca-client/clients
    #- FABRIC_CA_CLIENT_CSR_CN=caclient.papernet.hyperfabrics.com
    - FABRIC_CA_CLIENT_URL=http://caserver.papernet.hyperfabrics.com:7054
    - FABRIC_CA_CLIENT_MSPDIR=/etc/hyperledger/fabric-ca-client/msp
    #- FABRIC_CA_CLIENT_CSR_NAMES=(C=CA, ST=Onatrio, O=Hyperfabrics,)
    - FABRIC_CA_KEYFILE=/etc/hyperledger/fabric-ca-client/ca/key.pem
    - FABRIC_CA_CERTFILE=/etc/hyperledger/fabric-ca-client/ca/cert.pem
    - FABRIC_CA_CHAINFILE=/etc/hyperledger/fabric-ca-client/ca/cert.pem
    - FABRIC_CA_SERVER_PORT=7055
    - FABRIC_CA_BCSSP_SW_FILEKEYSTORE_KEYSTORE=/etc/hyperledger/fabric-ca-client/msp/keystore
    - FABRIC_CA_CLIENT_TLS_ENABLED=false
    - FABRIC_CA_CLIENT_TLS_CERTFILE=/etc/hyperledger/fabric-ca-client/tls/ca-cert.pem
    - FABRIC_CA_CLIENT_TLS_KEYFILE=/etc/hyperledger/fabric-ca-client/tls/prtivate.key
   working_dir: /etc/hyperledger/fabric-ca-client
  # command: sh -c 'fabric-ca-client enroll -u http://admin:adminpw@caserver.papernet.hyperfabrics.com:7054'
  # volumes:
  #   - "./fabric-ca-client/:/etc/hyperledger/fabric-ca-client"
   ports:
    - "7055:7055"


# Adding affiliations:
# fabric-ca-client affiliation add digibank
# fabric-ca-client affiliation add digibank.commercicalpaper
# export FABRIC_CA_CLIENT_HOME=/etc/hyperledger/fabric-ca-client/clients/digibank/digibank-peer1
# fabric-ca-client register --id.name peer0 --id.affiliation digibank.commercialpaper --id.attrs 'hf.Revoker=true,admin=true:ecert'