version: '2'

services:
  fabric-ca-server:
   image: hyperledger/fabric-ca:1.4.1
   container_name: caserver.papernet.hyperfabrics.com
   restart: always
   environment:
    - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    - FABRIC_CA_SERVER_CA_NAME=caserver.papernet.hyperfabrics.com
    - FABRIC_CA_SERVER_CSR_CN=caserver-papernetnet-hyperfabrics
    - FABRIC_CA_KEYFILE=/etc/hyperledger/fabric-ca-server/ca/key.pem
    - FABRIC_CA_CERTFILE=/etc/hyperledger/fabric-ca-server/ca/cert.pem
    - FABRIC_CA_CHAINFILE=/etc/hyperledger/fabric-ca-server/ca/cert.pem
    - FABRIC_CA_SERVER_PORT=7054
    - FABRIC_CA_SERVER_DEBUG=true
    - FABRIC_CA_BCSSP_SW_FILEKEYSTORE_KEYSTORE=/etc/hyperledger/fabric-ca-server/msp/keystore
    - FABRIC_CA_SERVER_TLS_ENABLED=false
    - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server/tls/ca-cert.pem
    - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server/tls/prtivate.key
    - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=127.0.0.1:9443
   working_dir: /etc/hyperledger/fabric-ca-server
   command: sh -c 'fabric-ca-server start -b admin:adminpw '
  # volumes:
   #  - "./fabric-ca-server/:/etc/hyperledger/fabric-ca-server"
   ports:
    - "7054:7054"
    - "9443:9443"

  
  
  
