   ca:
    container_name: ca.papernet.hyperfabrics.com 
    image: hyperledger/fabric-ca:$VERSION
    environment:
     - GOPATH=/opt/gopath
     - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
     - FABRIC_CA_SERVER_HOME=/etc/hyperledger/fabric-ca-server
     - FABRIC_CA_ROOT= /opt/gopath/src/github.com/hyperledger/fabric-ca
     - ROOT_CA_CERTIFICATE=/etc/hyperledger/fabric-ca-server/ca-cert.pem
     - FABRIC_CA_CLIENT_TLS_ENABLED=false
     - FABRIC_CA_CLIENT_TLS_CLIENT_CERTFILE=cert2.pem
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric-ca-server
    command: chmod 755 * & ./fabric-ca-server.sh
    volumes: ./network:/opt/gopath/src/github.com/hyperledger/fabric-ca-server
    ports:
    - "7054:7054"

  ca-client:
  container_name: caclient.hyperfabrics.com 
  image: hyperledger/fabric-ca:$VERSION
   environment:
    - GOPATH=/opt/gopath
    - CA_URL= 0.0.0.0:7054   
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - FABRIC_CA_CLIENT_HOME=/etc/hyperledger/fabric-ca
    - FABRIC_CA_CLIENT_TLS_ENABLED=false
    - FABRIC_CA_CLIENT_TLS_CLIENT_CERTFILE=cert2.pem
  working_dir: /opt/gopath/src/github.com/hyperledger/fabric-ca-server
  command:  chmod 755 * & ./fabric-ca-client.sh
  volumes: ./network:/opt/gopath/src/github.com/hyperledger/fabric-ca
  ports:
  - "7064:7054"
   
  
